# Generated by Django 4.1.7 on 2023-11-13 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
