# Generated by Django 4.2.6 on 2023-10-15 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_rename_startuplisting_startup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='technology',
            options={'verbose_name': 'Technology', 'verbose_name_plural': 'Technologies'},
        ),
    ]
