# Generated by Django 4.1.6 on 2023-10-24 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_remove_startup_location_startup_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='tag',
            field=models.ManyToManyField(blank=True, max_length=50, to='marketplace.tag'),
        ),
        migrations.AlterField(
            model_name='startup',
            name='technology_used',
            field=models.ManyToManyField(blank=True, max_length=50, to='marketplace.technology'),
        ),
    ]
