# Generated by Django 4.1.7 on 2023-11-12 02:14

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_alter_startup_company_name_alter_startup_tag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='due_diligence_documents',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='due_diligence_doc/'),
        ),
        migrations.AlterField(
            model_name='startup',
            name='legal_documents',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='legal_doc/'),
        ),
    ]
