# Generated by Django 4.1.7 on 2023-11-12 03:20

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_alter_startup_due_diligence_documents_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='country',
            field=django_countries.fields.CountryField(default='Nigeria', max_length=255),
        ),
    ]
