# Generated by Django 4.1.7 on 2023-11-12 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('drfpasswordless', '0005_auto_20201117_0410'),
        ('socialaccount', '0006_alter_socialaccount_extra_data'),
        ('authtoken', '0003_tokenproxy'),
        ('marketplace', '0007_alter_startup_due_diligence_documents_and_more'),
        ('token_blacklist', '0012_alter_outstandingtoken_user'),
        ('social_django', '0015_rename_extra_data_new_usersocialauth_extra_data'),
        ('account', '0005_emailaddress_idx_upper_email'),
        ('oauth2_provider', '0007_application_post_logout_redirect_uris'),
        ('authentication', '0006_rename_user_customuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='User',
        ),
    ]
